### ISSUE TITLE
Please allow this to work in any language

### ISSUE THREAD

**Issue by ndbroadbent** [vilic/vscode-es-quotes#10]
Hello,

Can you please allow the 'single quotes' <=> "double quotes" transformation to work in any language? There's no reason why this can't work anywhere else (e.g. Ruby).

Thanks!

**Comment by vilicvane** [comment]
Hi, actually there are reasons why it cannot work elsewhere.

It does not simply search for quotes around the cursor to apply the change. Instead, it parses the source file, locate string literal tokens, and then apply changes. And thus the source code parser won't work as expected in other languages because it is written according to ECMAScript standard.

**Comment by ndbroadbent** [comment]
Hi, thanks for the reply! But I keep coming back to this, because I'm using VSCode for Ruby development, and I'm really missing the ability to quickly switch between single and double quotes.

Would it be possible to change the code so that it does just search for quotes around the cursor? That seems like it would be a lot simpler, and then it would be able to work in any language.

No worries if not, but are you aware of any other quote transformation extensions? I can't seem to find any, so I might have to just write one myself.
